---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: latest

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-12.10
  - name: ubuntu-13.04
  - name: ubuntu-13.10

suites:
  - name: default
    run_list:
     - recipe[mythtv::default]
    attributes:
  - name: backend
    run_list:
     - recipe[mythtv::backend]
    attributes:
      mysql:
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass
  - name: frontend
    run_list:
     - recipe[mythtv::frontend]
    attributes:
  - name: airplay
    run_list:
     - recipe[mythtv::airplay]
    attributes:
      mythtv:
        raop_key:
          user: vagrant
